version: '3.8'

services:
  bbhunt-core:
    build: .
    volumes:
      - ./data:/data
      - ./config:/config
      - ./profiles:/config/profiles
    environment:
      - BBHUNT_GLOBAL_DATA_DIR=/data
      - BBHUNT_GLOBAL_CONFIG_DIR=/config
      - BBHUNT_GLOBAL_USER_AGENT=bbhunt-docker/0.1.0
      - BBHUNT_GLOBAL_PROFILE=base
    networks:
      - bbhunt-network
    command: ["--help"]

  redis:
    image: redis:alpine
    networks:
      - bbhunt-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Worker services for distributed scanning
  recon-worker:
    build: .
    volumes:
      - ./data:/data
      - ./config:/config
      - ./profiles:/config/profiles
    environment:
      - BBHUNT_GLOBAL_DATA_DIR=/data
      - BBHUNT_GLOBAL_CONFIG_DIR=/config
      - BBHUNT_GLOBAL_USER_AGENT=bbhunt-recon/0.1.0
      - BBHUNT_GLOBAL_PROFILE=base
      - BBHUNT_WORKER_TYPE=recon
    # Use the actual command structure your project uses
    command: ["run", "subdomain_enum", "--profile", "base"]
    depends_on:
      - redis
    networks:
      - bbhunt-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G

  scan-worker:
    build: .
    volumes:
      - ./data:/data
      - ./config:/config
      - ./profiles:/config/profiles
    environment:
      - BBHUNT_GLOBAL_DATA_DIR=/data
      - BBHUNT_GLOBAL_CONFIG_DIR=/config
      - BBHUNT_GLOBAL_USER_AGENT=bbhunt-scan/0.1.0
      - BBHUNT_GLOBAL_PROFILE=base
      - BBHUNT_WORKER_TYPE=scan
    # Use the actual command structure your project uses
    command: ["run", "web_scan", "--profile", "base"]
    depends_on:
      - redis
    networks:
      - bbhunt-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Web UI (optional)
  webui:
    image: nginx:alpine
    volumes:
      - ./webui:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - bbhunt-network
    depends_on:
      - bbhunt-core

networks:
  bbhunt-network:
    driver: bridge

volumes:
  redis-data: