# BBHunt default configuration

[global]
# Default data directory
data_dir = "~/.bbhunt/data"
# Default config directory
config_dir = "~/.bbhunt/config"
# Maximum memory usage in MB
max_memory = 4096
# Maximum CPU usage (number of cores)
max_cpu = 8
# Default user agent
user_agent = "bbhunt/0.1.0"
# Default profile
default_profile = "standard"

# Plugin configurations
[plugins.subdomain_enum]
enabled = true
tools = ["subfinder", "amass"]
default_options = { passive_only = false }

[plugins.web_scan]
enabled = true
tools = ["nuclei", "nikto"]
default_options = { mode = "standard" }

# External tool configurations
[tools.subfinder]
path = "subfinder"
passive_only = false

[tools.amass]
path = "amass"
passive_only = false

[tools.nuclei]
path = "nuclei"
templates_path = "~/.bbhunt/data/nuclei-templates"

[tools.nikto]
path = "nikto"

# Scan profiles
[profiles.quick]
max_concurrent_tasks = 8
scan_mode = "basic"
risk_level = "low"
timeout_seconds = 300

[profiles.standard]
max_concurrent_tasks = 4
scan_mode = "standard"
risk_level = "medium"
timeout_seconds = 600

[profiles.thorough]
max_concurrent_tasks = 2
scan_mode = "thorough"
risk_level = "high"
timeout_seconds = 1800