[global]
# Default data directory
data_dir = "~/.bbhunt/data"
# Default config directory
config_dir = "~/.bbhunt/config"
# Maximum memory usage in MB
max_memory = 4096
# Maximum CPU usage (number of cores)
max_cpu = 8
# Default user agent
user_agent = "bbhunt/0.1.0"
# Default profile
default_profile = "base"
# Profiles directory (relative to config_dir)
profiles_dir = "profiles"
# Templates directory (relative to config_dir)
templates_dir = "templates"

# External tool paths (can be overridden by profiles)
[tools.subfinder]
path = "subfinder"

[tools.amass]
path = "amass"

[tools.nuclei]
path = "nuclei"
templates_path = "~/.bbhunt/data/nuclei-templates"

[tools.httpx]
path = "httpx"

[tools.nikto]
path = "nikto"